language: node_js
node_js:
- '10'
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_script:
  # - psql -c 'create database jobly_test;' -U postgres
  - psql -c 'CREATE DATABASE jobly_test;' -U postgres
  - psql --dbname=jobly_test --file=jobly_test_seed.sql
script:
- npm run test