language: node_js
node_js:
- '10'
services:
  - postgresql
addons:
  postgresql: "12.3"
before_script:
  - psql -c 'create database jobly_test;' -U postgres
  - psql --dbname=jobly_test --file=jobly_test_seed.sql
script:
- npm run test